DINC+=externals/libp2pDWrapper
DINC+=externals/secp256k1
DINC+=units/basic
DINC+=units/hibon
# DINC+=units/services
# DINC+=units/network
# DINC+=units/wasm
# DINC+=units/crypto
# DINC+=units/hashgraph
# DINC+=units/foundation
# DINC+=units/funnel
# DINC+=units/gossip
# DINC+=units/dart
# DINC+=units/wamr
# DINC+=units/communication
# DINC+=units/tools
# DINC+=units/utils
# DINC+=units/wallet
# DINC+=units/monitor
