@startuml HealthCheck Sequence

skinparam Style strictuml
skinparam SequenceMessageAlign center
hide empty description
title HealthCheck Sequence Diagram

participant Tagionwallet as tagionwallet
participant SSLServise as SSL_service
participant SSLFiberService as SSL_fiber_service
participant TransactionService as transactionservice
participant TagionService as tagionservice

activate tagionwallet
tagionwallet -> SSL_service : connect
activate SSL_service
SSL_service -> SSL_fiber_service : send document with requested data
activate SSL_fiber_service
SSL_fiber_service -> transactionservice  : response
activate transactionservice
transactionservice -> tagionservice: HiRPC send
activate tagionservice
tagionservice -> transactionservice: send HiRPC response
deactivate tagionservice
transactionservice -> SSL_fiber_service: send respons 
deactivate transactionservice
SSL_fiber_service -> SSL_service: send
deactivate SSL_fiber_service
SSL_service -> tagionwallet: send response
deactivate tagionwallet
