@startuml HealthCheck Sequence

skinparam Style strictuml
skinparam SequenceMessageAlign center
hide empty description
title HealthCheck Sequence Diagram

participant Tagionwallet as tagionwallet
participant SSLSockete as SSL_socket
participant SSLFiberService as SSL_fiber_service
participant TransactionService as trans_service
participant TagionService as tagionservice

activate tagionwallet
tagionwallet -> SSL_socket : connect
activate SSL_socket
SSL_socket -> SSL_fiber_service : send("healthcheck")
activate SSL_fiber_service
SSL_fiber_service -> trans_service : send("healthcheck")
activate trans_service
trans_service -> tagionservice: send("transactionservice_task_name, "healthcheck"")
activate tagionservice
tagionservice -> trans_service: send(healthcheck responce))
deactivate tagionservice
trans_service -> SSL_fiber_service: send(healthcheck respons)
deactivate trans_service
SSL_fiber_service -> SSL_socket: send
deactivate SSL_fiber_service
SSL_socket -> tagionwallet: send response
deactivate tagionwallet
