@startuml HealthCheck Sequence

skinparam Style strictuml
skinparam SequenceMessageAlign center
hide empty description
title HealthCheck Sequence Diagram

participant Tagionwallet as tagionwallet
participant TagionService as tagionservice
participant TransactionService as transactionservice

activate tagionwallet
tagionwallet -> tagionservice : SSl send document with requested data
activate tagionservice
tagionservice ->  transactionservice: create, send hirpc respons
activate transactionservice
transactionservice -> tagionwallet: create, send SSL respons
deactivate tagionservice
deactivate transactionservice
deactivate tagionwallet
@enduml