@startuml

skinparam Style strictuml
skinparam SequenceMessageAlign center
hide empty description
title Recorder receiveRecorder sequence Diagram

control TranscriptService as task
control RecorderTask as recordertask
collections RecordFactory as factory
collections RecorderChain as chain
collections RecorderChainBlock as block


activate task
task -> task : bullseye = modifyDart(recorder)
task -> recordertask : send(recorder, dart_bullseye)
deactivate task


activate recordertask
recordertask -> recordertask : receiveRecorder(recorder, bullseye)
recordertask -> chain : getLastBlock()
chain --> recordertask : last_block
recordertask -> block : new RecorderChainBlock(recorder, last_block, bullseye, net)
recordertask -> chain : append(block)
deactivate recordertask

@enduml
