@startuml

skinparam Style strictuml
skinparam SequenceMessageAlign center
hide empty description
title Recorder startup opCall Sequence Diagram

participant Tagionservice as task
control RecorderTask as recordertask
collections RecorderChainFileStorage as storage
collections RecorderChain as chain

alt recorder_chain feature is enabled 
    task -> recordertask : spawn(opts)
activate recordertask
recordertask -> recordertask : opCall(opts)
recordertask -> storage : new RecorderChainFileStorage(folder_path, net)
storage --> recordertask : storage
recordertask -> chain : new RecorderChain(storage)
chain --> recordertask : recorder_chain

recordertask --> task : send(Control.LIVE);

loop while(!stop)
    recordertask -> recordertask : //Listening for concurrency signals.//
    note right : "See receiveRecorder \n diagram" 
end
deactivate recordertask


end


@enduml
