@startuml

skinparam Style strictuml
skinparam SequenceMessageAlign center
hide empty description
title Recorder startup opCall Sequence Diagram

participant Tagionservice as task
participant RecorderTask as recordertask
participant RecorderChainFileStorage as storage

recordertask -> recordertask : opCall(opts)
recordertask -> storage : new RecorderChainFileStorage(folder_path, net)
recordertask -> recordertask : new RecorderChain(storage)
recordertask -> task : send(Control.LIVE);

loop while(!stop)
    recordertask -> recordertask : receive(recorder, bullseye)
    note right : "See receiveRecorder \n diagram" 
end


@enduml
