#DC?=dmd
export GODEBUG:=cgocheck=0
ONETOOL?=1
DEBUGGER?=ddd
VERBOSE_COMPILER_ERRORS=1
# SECP256K1_DEBUG=1
# USE_SYSTEM_LIBS=1 # Compile with systemdependencies

export TEST_STAGE:=commit
export SEED:=$(shell git rev-parse HEAD)

RELEASE_DFLAGS+=$(DOPT)

ifdef USE_SYSTEM_LIBS
NNG_ENABLE_TLS=1
endif

ifndef DEBUG_DISABLE
DFLAGS+=$(DDEBUG_SYMBOLS)
endif

DFLAGS+=$(DVERSION)=REDBLACKTREE_SAFE_PROBLEM
DFLAGS+=$(DVERSION)=NET_HACK




# Extra DFLAGS for the testbench 
BDDDFLAGS+=$(DDEBUG_SYMBOLS)
BDDDFLAGS+=$(DEXPORT_DYN)

INSTALL?=$(HOME)/bin
