@startuml Healthcheck State
skinparam Style strictuml
skinparam SequenceMessageAlign center
title Healthcheck State Diagram
[*] -> Create_SSLSocket_client_in_tagionwallet
Create_SSLSocket_client_in_tagionwallet --> Client_connect_in_tagionwallet: Check_connection
Client_connect_in_tagionwallet --> Successful_connection
Client_connect_in_tagionwallet --> Failed_connection
Successful_connection --> Create_send_hirps_sender_for_request_healthcheck_data
Create_send_hirps_sender_for_request_healthcheck_data --> TagionService
TagionService --> TransactionService
TransactionService --> Receive_data_in_tagionwallet
Failed_connection --> Health_check_failed
Receive_data_in_tagionwallet --> [*]
Health_check_failed --> [*]
@enduml

