help:
	$(call log.header, help)
	$(call log.kvp, make help, Show this help)
	$(call log.separator)
	$(call log.kvp, make info, Show info about this tagion/maker repository)
	$(call log.separator)
	$(call log.kvp, make wrap/all, Compile wrappers for the host platform)
	$(call log.kvp, make lib/all, Compile libraries for the host platform)
	$(call log.kvp, make bin/all, Compile binaries for the host platform)
	$(call log.separator)
	$(call log.kvp, make wrap/[specific], Compile [specific] wrapper for the host platform)
	$(call log.kvp, make lib/[specific], Compile [specific] lib for the host platform)
	$(call log.kvp, make bin/[specific], Compile [specific] bin for the host platform)
	$(call log.separator)
	$(call log.kvp, make wrap/[specific] PLATFORM=apple-darwin-x86_64, Cross-compile [specific] wrapper for apple-darwin-x86_64)
	$(call log.kvp, make lib/[specific] PLATFORM=apple-darwin-x86_64, Cross-compile [specific] lib for apple-darwin-x86_64)
	$(call log.kvp, make bin/[specific] PLATFORM=apple-darwin-x86_64, Cross-compile [specific] bin for apple-darwin-x86_64)
	$(call log.separator)
	$(call log.kvp, make clean, Clean build directory)
	$(call log.close)
