@startuml Node Discovering State

skinparam Style strictuml
skinparam SequenceMessageAlign center
hide empty description
title Node Discovering State Diagram

[*] -> OfflineState
OfflineState --> InitNodesInDB : Initializing DB with init nodes
InitNodesInDB --> Discovering
state Discovering {
    state unvisitedChoice <<choice>>
    [*] -> HavingListOfActiveNodes
    HavingListOfActiveNodes --> unvisitedChoice
    unvisitedChoice --> TakingNextNode : exist not \nvisited nodes
    unvisitedChoice --> [*] : all nodes visited/\nno nodes in list

    TakingNextNode --> VerifiyingNode
    VerifiyingNode -> VerifiyingNode

    state trustedChoice <<choice>>
    VerifiyingNode --> trustedChoice
    trustedChoice --> unvisitedChoice : not trusted
    trustedChoice --> SyncingWithNode : trusted

    SyncingWithNode --> UpdatingListOfNodes
    UpdatingListOfNodes --> HavingListOfActiveNodes
}

Discovering --> NodeIsUpToDate
NodeIsUpToDate --> [*]

@enduml