CONFIGUREFLAGS_SECP256K1 += AR=$(TOOLCHAIN)/bin/llvm-ar
CONFIGUREFLAGS_SECP256K1 += CC=$(TOOLCHAIN)/bin/$(MTRIPLE)$(CROSS_ANDROID_API)-clang
CONFIGUREFLAGS_SECP256K1 += AS=$(TOOLCHAIN)/bin/$(MTRIPLE)$(CROSS_ANDROID_API)-clang
CONFIGUREFLAGS_SECP256K1 += CXX=$(TOOLCHAIN)/bin/$(MTRIPLE)$(CROSS_ANDROID_API)-clang++
CONFIGUREFLAGS_SECP256K1 += LD=$(TOOLCHAIN)/bin/ld
CONFIGUREFLAGS_SECP256K1 += RANLIB=$(TOOLCHAIN)/bin/llvm-ranlib
CONFIGUREFLAGS_SECP256K1 += STRIP=$(TOOLCHAIN)/bin/llvm-strip
CONFIGUREFLAGS_SECP256K1 += CFLAGS="-arch $(CROSS_ARCH) -fpic -g -Os -pipe -isysroot $(CROSS_SYSROOT)"