/Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/tagionboot.o: \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/bin-boot/tagion/tagionboot.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/file.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/time.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/traits.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/object.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/attribute.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/hash.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/entrypoint.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/appending.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/comparison.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/equality.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/casting.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/concatenation.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/construction.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/capacity.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/dassert.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/atomic.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/attributes.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/atomic.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/ldc/intrinsics.di \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/destruction.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/moving.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/postblit.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/switch_.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/exception.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/time.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/stdc/time.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/sys/types.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/config.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/config.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/stdint.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/stddef.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/signal.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/wchar_.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/stdarg.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/stdio.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/string.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/time.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/signal.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/sys/time.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/sys/select.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/darwin/mach/kern_return.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/datetime/date.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/traits.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/meta.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/range/primitives.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/typecons.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/format/package.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/vararg.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/exception.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/format/internal/read.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/format/internal/write.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/internal/attributes.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/datetime/systime.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/datetime/timezone.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/errno.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/stdlib.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/string.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/internal/cstring.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/range/package.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/array.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/functional.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/range/interfaces.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/dirent.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/fcntl.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/sys/stat.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/unistd.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/inttypes.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/inttypes.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/utime.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/algorithm/iteration.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/HiBON.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/container/package.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/container/array.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/container/util.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/container/binaryheap.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/container/dlist.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/container/rbtree.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/container/slist.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/conv.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/ascii.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/lifetime.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/HiBONRecord.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-basic/tagion/basic/Basic.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/string.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/uni/package.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/internal/unicode_tables.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/algorithm/comparison.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/algorithm/searching.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/bitmanip.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/system.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/HiBONBase.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-utils/tagion/utils/StdTime.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/datetime/package.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/datetime/interval.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/HiBONException.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-basic/tagion/basic/TagionExceptions.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/BigNumber.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/internal/math/biguintnoasm.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/bigint.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/internal/math/biguintcore.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/bitop.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/volatile.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/base64.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-utils/tagion/utils/LEB128.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/Document.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-basic/tagion/basic/Message.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/json.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/stdio.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/algorithm/mutation.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/sys/posix/stdio.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/HiBONJSON.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-hibon/tagion/hibon/HiBONtoText.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-utils/tagion/utils/Miscellaneous.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-crypto/tagion/crypto/SecureNet.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-crypto/tagion/crypto/SecureInterfaceNet.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-basic/tagion/basic/ConsensusExceptions.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-crypto/tagion/crypto/aes/AESCrypto.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-funnel/tagion/script/StandardRecords.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-funnel/tagion/script/ScriptBase.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-funnel/tagion/script/TagionCurrency.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/getopt.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-dart/tagion/dart/Recorder.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-dart/tagion/dart/DARTException.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/path.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/lifetime.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/convert.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/math.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/math.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/math.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/stdc/fenv.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/ldc/attributes.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/memory.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/internal/array/utils.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/core/checkedint.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/utf.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/algorithm/package.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/algorithm/setops.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/algorithm/sorting.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-crypto/tagion/crypto/secp256k1/NativeSecp256k1.d \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-crypto/tagion/crypto/secp256k1/c/secp256k1.di \
  /Users/vladpazych/Workspace/tagion/code/exp4/src/lib-crypto/tagion/crypto/secp256k1/c/secp256k1_ecdh.di \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/internal/unicode_grapheme.d \
  /Users/vladpazych/Applications/ldc2-1.26.0-osx-arm64/bin/../import/std/internal/memory.d

/Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/bin/tagionboot: /Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/tagionboot.o /Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/libbasic.o /Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/libcrypto.o /Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/libdart.o /Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/libfunnel.o /Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/libhibon.o /Users/vladpazych/Workspace/tagion/code/exp4/build/arm64-unknown-darwin/tmp/libutils.o
