include $(DIR_TUB)/compile/map.mk
include $(DIR_TUB)/compile/ways.mk
include $(DIR_TUB)/compile/init.mk
include $(DIR_TUB)/compile/clean.mk
include $(DIR_TUB)/compile/clone.mk
include $(DIR_TUB)/compile/goals.mk
include $(DIR_TUB)/compile/common.mk
include $(DIR_TUB)/compile/resolve.mk
include $(DIR_TUB)/compile/compile.mk