
LIBP2PGOWRAPPER_DIROOT := ${call dir.resolve, p2p/cgo}
LIBP2PGOWRAPPER_PACKAGE := p2p.cgo

LIBP2PGOWRAPPER_DFILES := ${wildcard ${call dir.resolve, p2p}/*.d}

$(LIBP2PGOWRAPPER_DIROOT)/libp2pgowrapper.di: DSTEPFLAGS += --global-import=$(LIBP2PGOWRAPPER_PACKAGE).c_helper

${call DSTEP_DO,$(LIBP2PGOWRAPPER_PACKAGE),$(DTMP_P2PGOWRAPPER),$(LIBP2PGOWRAPPER_DIROOT),$(LIBP2PGOWRAPPER_DFILES)}
