#!/usr/bin/env bash

ORIGIN=$(pwd)
SEP="------------------------------"

for DIR in $(ls src/libs); do
    echo 
    echo $SEP lib/$DIR

    cd "$ORIGIN/src/libs/$DIR/"
    git $@ 

    echo $SEP
    echo 
done

# TODO: Optimize code duplication
for DIR in $(ls src/bins); do
    echo 
    echo $SEP bin/$DIR

    cd "$ORIGIN/src/bins/$DIR/"
    git $@ 

    echo $SEP
    echo 
done