help: info
	$(call log.header, make :: help)
	$(call log.kvp, make help, Show this help)
	$(call log.separator)
	$(call log.kvp, make info, Show info about tagil-maker repository)
	$(call log.separator)
	$(call log.kvp, make lib/[specific], Compile [specific] lib for the host platform)
	$(call log.kvp, make bin/[specific], Compile [specific] bin for the host platform)
	$(call log.kvp, make wrap/[specific], Compile [specific] wrapper for the host platform)
	$(call log.separator)
	$(call log.kvp, make test/lib/[specific], Test [specific] lib for the host platform)
	$(call log.kvp, make test/bin/[specific], Test [specific] bin for the host platform)
	$(call log.separator)
	$(call log.kvp, make clean, Clean build directory)
	$(call log.close)
