#!/usr/bin/env bash

PWD=$(pwd)

git submodule update --init --recursive

cp ./tub/.setup/Makefile .
cp ./tub/.setup/configure .

cp ./tub/.setup/config.submodule.mk .

echo "Installing local git aliases..."
./tub/.setup/gitconfig