#!/usr/bin/env bash

ORIGIN=$(pwd)
SEP="------------------------------"

for DIR in $(ls src/libs); do
    echo 
    echo $SEP lib/$DIR

    cd "$ORIGIN/src/libs/$DIR/"
    $@ 

    echo $SEP
    echo 
done