name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  GH_TOKEN: ${{ secrets.GITBOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: docker build
        run: | 
          docker build . -t tagion/tagion:${{ github.ref_name }}
      - name: Extract static binary
        run: |
          id=$(docker create tagion/tagion:${{ github.ref_name }})
          docker cp $id:/usr/local/bin/tagion tagion
          docker rm -v $id

      - name: Create Package
        run: |
          mkdir -p build/x86_64-linux/bin/
          mv tagion build/x86_64-linux/bin/
          make clean-pkg bin-pkg tar-pkg
          make clean-pkg bin-pkg deb-pkg

      - name: Release
        run: |
          gh release create ${{ github.ref_name }} build/*.tar.gz build/*.deb --prerelease 
