name: Vibe-service workflow
on:
  workflow_dispatch:
  push: 
    branches: 
      - current
      
env:
  GITBOT_TOKEN: ${{ secrets.GITBOT_TOKEN }}
  
jobs:
  uodate_version:
    runs-on: dartservice-back    
    steps:
      - name: get repository
        run: |
          cd ..
          git clone git@github.com:tagion/tagion.git || echo "repo already exists"
      - name: pull
        run: |
          git clean -f && git restore . 
          git checkout current
          git pull
      - name: update version
        run: |
          export GH_TOKEN=${{ env.GITBOT_TOKEN }}
          id
          pwd
          ls -l
  
